config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'
  #get 'users/edit'
  #get 'books/new'
  #get 'books/index'
  #get 'books/show'
  #get 'homes/top'
  devise_for :users
  root to:"homes#top"
  get 'home/about' => 'homes#about'
  resources :books, only: [:new,:create,:index,:edit,:update,:show,:destroy] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments, only:[:create,:destroy]
  end
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    # get 'daily_posts' => 'users#daily_posts'
  end
  get 'search' => 'searches#search_list'

  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }#今日
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }#前日
  scope :created_2day_ago, -> { where(created_at: 2.day.ago.all_day) }#2日前
  scope :created_3day_ago, -> { where(created_at: 3.day.ago.all_day) }#3日前
  scope :created_4day_ago, -> { where(created_at: 4.day.ago.all_day) }#4日前
  scope :created_5day_ago, -> { where(created_at: 5.day.ago.all_day) }#5日前
  scope :created_6day_ago, -> { where(created_at: 6.day.ago.all_day) }#6日前
  scope :created_this_week, -> { where(created_at: 6.day.ago.beginning_of_day..Time.zone.now.end_of_day) }#今週
  scope :created_last_week, -> { where(created_at: 2.week.ago.beginning_of_day..1.week.ago.end_of_day) }#前週

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.search_for(search,word)
    if search == 'perfect'
      Book.where(title: word)
    elsif search == 'forward'
      Book.where('name LIkE ?', word + '%')
    elsif search == 'backward'
      Book.where('name LIkE ?', '%' + word)
    else
      Book.where('name LIKE ?', '%' + word + '%')
    end
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @books = Book.all
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_index.html.erb
 <table class='table table-hover table-inverse'>
   <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
    <tr id="book_<%= book.id %>">
      <td><%= link_to user_path(book.user_id) do %>
        <%= image_tag book.user.get_profile_image(50,50) %>
        <% end %>
      </td>
      <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
      <td><%= book.body %></td>
      <td class="favorite-btn">
        <%= render 'favorites/favorite-btn', book: book %>
      </td>
      <td class="comments-count">
        コメント件数:<%= book.book_comments.count %>
      </td>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/books/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image(100,100) %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followings.count, user_followings_path(user) %></tr>
  </tr>
</table>


<div class='row'>
  <% if user.name != "guestuser" %>
    <% if current_user != user %>
      <% if current_user != user %>
        <% if current_user.follow?(user) %>
          <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
        <i class="fas fa-user-cog"></i>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render 'users/error', book: @book %>

      <%= render 'users/form', book: @book %>

      <div>
        <%= link_to 'Show', book_path(@book.id) %> |
        <%= link_to 'Back', books_path %></div>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div>
  <%= flash[:success] %>
</div>
<%= render 'users/error', book: @book %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h1>User info</h1>
      <%= render 'info', user: current_user %>
      <h1 class="mt-3">New book</h1>
      <%= render 'users/form', book: @book %>
    </div>
      <div class="col-md-8 offset-md-1">
        <h1>Books</h1>
        <%= render 'index', books: @books %>
      </div>
    </div>
  </div>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div>
  <%= flash[:success] %>
</div>
<%= render 'users/error', book: @book %>

<div class="container px-5 px-sm-0 box">
  <div class="row">
    <div class="col-md-3">
      <h1>User info</h1>
      <%= render 'info', user: @book.user %>

      <h1 class="mt-3">New book</h1>
      <%= render 'users/form', book: @book_new %>
    </div>
      <div class="col-md-8 offset-md-1">
         <h1>Book detail</h1>
        <table class="table">
          <tr id="book_<%= @book.id %>">
            <td>
            <%= link_to user_path(@book.user_id) do %>
              <%= image_tag @book.user.get_profile_image(100,100) %><br>
              <%= @book.user.name %>
            <% end %>
            </td>
            <td><%= link_to @book.title , book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path, class: "btn btn-sm btn-primary" %></td>
            <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger"%></td>
            <% end %>
            <td class="favorite-btn">
              <%= render 'favorites/favorite-btn', book: @book %>
            </td>
            <td class="comments-count">
              コメント件数:<%= @book.book_comments.count %>
            </td>
          </tr>
        </table>
        <table class="table book_comments">
          <%= render 'book_comments/comment-btn', book: @book %>
        </table>
        <%= form_with model: [@book, @book_comment], local: false do |f| %>
          <%= f.text_area :comment, rows:"3" %>
          <%= f.submit "送信" %>
        <% end %>
      </div>
    </div>
  </div>