config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'
  #get 'users/edit'
  #get 'books/new'
  #get 'books/index'
  #get 'books/show'
  #get 'homes/top'
  devise_for :users
  root to:"homes#top"
  get 'home/about' => 'homes#about'
  resources :books, only: [:new,:create,:index,:edit,:update,:show,:destroy] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments, only:[:create,:destroy]
  end
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    # get 'daily_posts' => 'users#daily_posts'
  end
  get 'search' => 'searches#search_list'

  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search_list
    @range = params[:range]
    @search = params[:search]
    @word = params[:word]
    if @range == "Book"
      @books = Book.search_for(@search, @word)
    else
      @users = User.search_for(@search, @word)
    end
  end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/search_list.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col">
      <% if @range == "Book" %>
      <h1>Book Search For "<%= @word %>"</h1>
        <table class='table'>
          <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <%  @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user_id) do %>
                <%= image_tag book.user.get_profile_image(50,50) %>
              <% end %>
            </td>
            <td><%= link_to book_path(book.id) do %><%= book.title %><% end %></td>
            <td><%= book.body %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <h1>User Search For "<%= @word %>"</h1>
      <table class='table'>
        <thead>
          <tr>
            <th>Image</th>
            <th>Name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <%  @users.each do |user| %>
          <tr>
            <td><%= image_tag user.get_profile_image(50,50) %></td>
            <td><%= user.name %></td>
            <td><%= link_to "Show", user_path(user.id) %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% end %>
    </div>
  </div>
</div>