config/routes.rb
Rails.application.routes.draw do
  #get 'users/show'
  #get 'users/edit'
  #get 'books/new'
  #get 'books/index'
  #get 'books/show'
  #get 'homes/top'
  devise_for :users
  root to:"homes#top"
  get 'home/about' => 'homes#about'
  resources :books, only: [:new,:create,:index,:edit,:update,:show,:destroy] do
    resource :favorites, only:[:create,:destroy]
    resources :book_comments, only:[:create,:destroy]
  end
  resources :users, only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    # get 'daily_posts' => 'users#daily_posts'
  end
  get 'search' => 'searches#search_list'

  devise_scope :user do
    post 'users/guest_sign_in', to:'users/sessions#guest_sign_in'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li>
                <%= link_to user_path(current_user.id),class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%=  link_to users_path,class: 'nav-link text-light' do %>
                <i class="fas fa-users"></i> Users
                <% end %>
              </li>
              <li>
                <%=  link_to books_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-book-open"></i> Books
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-out-alt"></i> Log out
                <% end %>
              </li>
              <% else %>
              <li>
                <%= link_to root_path,class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i> Home
                <% end %>
              </li>
              <li>
                <%= link_to home_about_path,class: 'nav-link text-light' do %>
                <i class="fas fa-link"></i> About
                <% end %>
              </li>
              <li>
                <%= link_to new_user_registration_path,class: 'nav-link text-light' do %>
                <i class="fas fa-user-plus"></i> Sign up
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path ,class: 'nav-link text-light' do %>
                <i class="fas fa-sign-in-alt"></i> Log in
                <% end %>
              </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
      <div class="search">
        <div class="container">
          <div class="row">
            <div class="col">
            <% if user_signed_in? %>
              <%= form_with url: search_path, local: true, method: :get do |f| %>
                <%= f.text_field :word %>
                <%= f.select :range, options_for_select([["Book"],["User"]]) %>
                <%= f.select :search, options_for_select([["完全一致","perfect"],["前方一致","forward"],["後方一致","backward"],["部分一致","partial"]]) %>
                <%= f.submit '検索' %>
              <% end %>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    </header>
      <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>